### ISSUE TITLE
ES cluster hits "Data too large"

### ISSUE THREAD

**Issue by leahnp** [samsung-cnct/elasticsearch-kubernetes#3]
Cluster stops functioning after a few days of data (this behavior was observed repeatedly on clusters with 9 cluster nodes, size m4.xlarge). I need help understanding where this limit of 2gb is coming from and if I can adjust it or if we should alter something in our core deployment here. In this state Kibana cannot access data. Current repro: deploy central logging system with reference logging app, elasticsearch will hit this within 2-4 days. 

Currently two data nodes and one master node are showing errors like:

Data: ```[2017-05-05T21:58:11,435][WARN ][o.e.a.b.TransportShardBulkAction] [elasticsearch-data-2] [[logstash-2017.05.05][3]] failed to perform indices:data/write/bulk[s] on replica [logstash-2017.05.05][3], node[akEojbbHTnO7iJilAiHIcw], [R], recovery_source[peer recovery], s[INITIALIZING], a[id=wk6JSmtyS1Cs2pUaVfLnHw], unassigned_info[[reason=REALLOCATED_REPLICA], at[2017-05-05T21:58:00.673Z], delayed=false, details[existing allocation of replica to [{elasticsearch-data-0}{KFHPSGlmQsW-ZZMkXwfqzQ}{1DavJfjyROu_46Djbrit2A}{10.128.28.3}{10.128.28.3:9300}] cancelled, sync id match found on node [{elasticsearch-data-1}{akEojbbHTnO7iJilAiHIcw}{cgxxt1dHS4W7eNWiQS2I2g}{10.129.96.4}{10.129.96.4:9300}]], allocation_status[no_attempt]]
org.elasticsearch.transport.RemoteTransportException: [elasticsearch-data-1][10.129.96.4:9300][indices:data/write/bulk[s][r]]
Caused by: org.elasticsearch.common.breaker.CircuitBreakingException: [parent] Data too large, data for [<transport_request>] would be larger than limit of [2230452224/2gb]```

Master: ```[2017-05-06T00:07:50,676][WARN ][o.e.c.a.s.ShardStateAction] [elasticsearch-master-0] [logstash-2017.05.06][1] received shard failed for shard id [[logstash-2017.05.06][1]], allocation id [gP4vtmvLSaiEyr5XPqh3rQ], primary term [1], message [failed to perform indices:data/write/bulk[s] on replica [logstash-2017.05.06][1], node[akEojbbHTnO7iJilAiHIcw], [R], s[STARTED], a[id=gP4vtmvLSaiEyr5XPqh3rQ]], failure [RemoteTransportException[[elasticsearch-data-1][10.129.96.4:9300][indices:data/write/bulk[s][r]]]; nested: CircuitBreakingException[[parent] Data too large, data for [<transport_request>] would be larger than limit of [2230452224/2gb]]; ]
org.elasticsearch.transport.RemoteTransportException: [elasticsearch-data-1][10.129.96.4:9300][indices:data/write/bulk[s][r]]
Caused by: org.elasticsearch.common.breaker.CircuitBreakingException: [parent] Data too large, data for [<transport_request>] would be larger than limit of [2230452224/2gb]
	at org.elasticsearch.indices.breaker.HierarchyCircuitBreakerService.checkParentLimit(HierarchyCircuitBreakerService.java:211) ~[elasticsearch-5.0.0.jar:5.0.0]
	at org.elasticsearch.common.breaker.ChildMemoryCircuitBreaker.addEstimateBytesAndMaybeBreak(ChildMemoryCircuitBreaker.java:128) ~[elasticsearch-5.0.0.jar:5.0.0]
	at org.elasticsearch.transport.TcpTransport.handleRequest(TcpTransport.java:1295) [elasticsearch-5.0.0.jar:5.0.0]
	at org.elasticsearch.transport.TcpTransport.messageReceived(TcpTransport.java:1205) [elasticsearch-5.0.0.jar:5.0.0]
	at org.elasticsearch.transport.netty4.Netty4MessageChannelHandler.channelRead(Netty4MessageChannelHandler.java:74) [transport-netty4-5.0.0.jar:5.0.0]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:372) [netty-transport-4.1.5.Final.jar:4.1.5.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:358) [netty-transport-4.1.5.Final.jar:4.1.5.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:350) [netty-transport-4.1.5.Final.jar:4.1.5.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293) [netty-codec-4.1.5.Final.jar:4.1.5.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:280) [netty-codec-4.1.5.Final.jar:4.1.5.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:396) [netty-codec-4.1.5.Final.jar:4.1.5.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:248) [netty-codec-4.1.5.Final.jar:4.1.5.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:372) [netty-transport-4.1.5.Final.jar:4.1.5.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:358) [netty-transport-4.1.5.Final.jar:4.1.5.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:350) [netty-transport-4.1.5.Final.jar:4.1.5.Final]
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86) [netty-transport-4.1.5.Final.jar:4.1.5.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:372) [netty-transport-4.1.5.Final.jar:4.1.5.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:358) [netty-transport-4.1.5.Final.jar:4.1.5.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:350) [netty-transport-4.1.5.Final.jar:4.1.5.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334) [netty-transport-4.1.5.Final.jar:4.1.5.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:372) [netty-transport-4.1.5.Final.jar:4.1.5.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:358) [netty-transport-4.1.5.Final.jar:4.1.5.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926) [netty-transport-4.1.5.Final.jar:4.1.5.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:129) [netty-transport-4.1.5.Final.jar:4.1.5.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:610) [netty-transport-4.1.5.Final.jar:4.1.5.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:513) [netty-transport-4.1.5.Final.jar:4.1.5.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:467) [netty-transport-4.1.5.Final.jar:4.1.5.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:437) [netty-transport-4.1.5.Final.jar:4.1.5.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:873) [netty-common-4.1.5.Final.jar:4.1.5.Final]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]```

**Comment by DStorck** [comment]
This issue was moved to samsung-cnct/container-elasticsearch#1
